### ISSUE TITLE
no valid transports or upstreams available

### ISSUE THREAD

**Issue by zyrill** [getdnsapi/stubby#46] opened 2017-11-18 16:45 UTC
Hi guys

I can't seem to get stubby to behave on my (linux) router. I'm running stubby successfully on my windows machine. But on the router, I always get errors when testing if the stubby works with `dig @192.168.66.1 -p 453 www.heise.de`.

Could you guys help me out pls? I'm sure I've just forgotten something, but I can't figure out what. I've also uploaded the error messages for better readability to https://pastebin.com/V696AZtQ

Googling for a few hours didn't provide me with a clue how to solve the problem, sadly - but I think it may have something to do with missing intermediate certificates? But where would I put those?

So here's the message:
`stubby -l
[16:36:54.381273] STUBBY: Read config from file /mod/root/.stubby.yml
[16:36:54.383812] STUBBY: Starting DAEMON....
[16:36:57.602079] STUBBY: 145.100.185.15                           : Conn opened: TLS - Strict Profile
[16:36:57.695453] STUBBY: 145.100.185.15                           : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:57.700220] STUBBY: 145.100.185.15                           : Conn closed   : Transport=TLS - *Failure*
[16:36:57.704930] STUBBY: 145.100.185.16                           : Conn opened: TLS - Strict Profile
[16:36:57.708250] STUBBY: 145.100.185.15                           : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:57.713019] STUBBY: 145.100.185.15                           : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:57.713692] STUBBY: 145.100.185.15                           : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:57.794389] STUBBY: 145.100.185.16                           : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:57.798158] STUBBY: 145.100.185.16                           : Conn closed   : Transport=TLS - *Failure*
[16:36:57.801759] STUBBY: 185.49.141.37                            : Conn opened: TLS - Strict Profile
[16:36:57.803273] STUBBY: 145.100.185.16                           : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:57.803965] STUBBY: 145.100.185.16                           : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:57.804634] STUBBY: 145.100.185.16                           : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:57.857548] STUBBY: 185.49.141.37                            : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:57.859055] STUBBY: 185.49.141.37                            : Conn closed   : Transport=TLS - *Failure*
[16:36:57.861521] STUBBY: 2001:610:1:40ba:145:100:185:15           : Conn opened: TLS - Strict Profile
[16:36:57.862118] STUBBY: 185.49.141.37                            : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:57.864410] STUBBY: 185.49.141.37                            : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:57.870816] STUBBY: 185.49.141.37                            : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:57.937756] STUBBY: 2001:610:1:40ba:145:100:185:15           : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:57.940717] STUBBY: 2001:610:1:40ba:145:100:185:15           : Conn closed   : Transport=TLS - *Failure*
[16:36:57.945270] STUBBY: 2001:610:1:40ba:145:100:185:16           : Conn opened: TLS - Strict Profile
[16:36:57.947053] STUBBY: 2001:610:1:40ba:145:100:185:15           : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:57.950262] STUBBY: 2001:610:1:40ba:145:100:185:15           : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:57.953177] STUBBY: 2001:610:1:40ba:145:100:185:15           : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:58.007956] STUBBY: 2001:610:1:40ba:145:100:185:16           : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:58.009320] STUBBY: 2001:610:1:40ba:145:100:185:16           : Conn closed   : Transport=TLS - *Failure*
[16:36:58.011621] STUBBY: 2a04:b900:0:100::38                      : Conn opened: TLS - Strict Profile
[16:36:58.012227] STUBBY: 2001:610:1:40ba:145:100:185:16           : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:58.013992] STUBBY: 2001:610:1:40ba:145:100:185:16           : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:58.017795] STUBBY: 2001:610:1:40ba:145:100:185:16           : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:58.064408] STUBBY: 2a04:b900:0:100::38                      : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:58.068870] STUBBY: 2a04:b900:0:100::38                      : Conn closed   : Transport=TLS - *Failure*
[16:36:58.073570] STUBBY: 89.233.43.71                             : Conn opened: TLS - Strict Profile
[16:36:58.077700] STUBBY: 2a04:b900:0:100::38                      : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:58.082302] STUBBY: 2a04:b900:0:100::38                      : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:58.087956] STUBBY: 2a04:b900:0:100::38                      : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:58.164430] STUBBY: 89.233.43.71                             : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:58.169350] STUBBY: 89.233.43.71                             : Conn closed   : Transport=TLS - *Failure*
[16:36:58.174020] STUBBY: 51.15.70.167                             : Conn opened: TLS - Strict Profile
[16:36:58.174591] STUBBY: 89.233.43.71                             : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:58.175285] STUBBY: 89.233.43.71                             : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:58.175885] STUBBY: 89.233.43.71                             : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0
[16:36:58.252260] STUBBY: 51.15.70.167                             : Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"
[16:36:58.255366] STUBBY: 51.15.70.167                             : Conn closed   : Transport=TLS - *Failure*
[16:36:58.258880] STUBBY: *FAILURE* no valid transports or upstreams available!
[16:36:58.260495] STUBBY: 51.15.70.167                             : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[16:36:58.263636] STUBBY: 51.15.70.167                             : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[16:36:58.264774] STUBBY: 51.15.70.167                             : Upstream   : TLS - Conns=     0, Conn_fails=     0, Conn_shuts=      0, Backoffs     =     0`

**Comment by wtoorop** [comment] 2017-11-21 15:02
Yes, this is due to a missing certificate store.
What directory does `openssl version -d` return?  Is there a cert directory underneath it?
Even though you might fix the issue by provisioning a store... I do think that it should not be needed when a sha256 pinset is given, so this is a bug that needs to be resolved.  We have an getdns issue on this b.t.w. See: getdnsapi/getdns#293

**Comment by wtoorop** [comment] 2017-11-21 15:33
Although it appears unrelated to getdnsapi/getdns#293 on the surface, it actually is not, and the solution mentioned in there should resolve this too.  So that is why I labeled this duplicate.

**Comment by wtoorop** [comment] 2017-11-29 14:14
Well... getdns uses the OpenSSL [`SSL_CTX_load_verify_locations`](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_load_verify_locations.html) function.  It is hard to tell what the location would be without the openssl command line tool (maybe we could provide this information via the [`getdns_context_get_api_information function`](https://getdnsapi.net/functions/getdns_context_get_api_information.html) (i.e. `-i` option with stubby) in the next getdns release), but it is quite often `/etc/ssl/certs`.
Although it is a bug that you need these even if you have SPKI pinsets, it might still be a good idea to have the default locations configurable in getdns anyway (for upstreams which need to be authenticated by only name).
Oh... b.t.w. I forgot to mention, but you could bypass the error by disabling authentication too.
Of course you'd have only opportunistic DNS-over-TLS, but maybe better than nothing for the time being.

**Comment by Kdmeizk** [comment] 2018-02-17 23:32
I had no choice but to reinstall Windows 7. Since this, Stubby gives a same message as in this bug:

> *Failure* -  (20) "unable to get local issuer certificate"

So, I assume it is related to this bug.

**Comment by saradickinson** [comment] 2018-02-19 11:40
@Kdmeizk Hmm, a clean install of Stubby shouldn't give this error unless there is something wrong with the certificate. What version of Stubby are you using, how did you install and are you using the default Stubby config?

**Comment by Kdmeizk** [comment] 2018-02-21 01:31
@saradickinson Ahaha, I tested until the latest optional update from Windows Update related to certificates and/or TLS, and it is this very last update which solved the problem. I will test more precisely later to find out what optional updates are concerned, or maybe you know them already?

It seems KB3172605 solved the problem, but I got it by installing other optional updates I believe. I will check.

PS: I have the latest version of Stubby for Windows (0.2.0), default/clean config

**Comment by saradickinson** [comment] 2018-02-21 11:57
@Kdmeizk thanks for the info! I've added a link to this page as a known issue on the wiki for the Windows installer:
https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby

**Comment by Kdmeizk** [comment] 2018-02-28 21:28
@saradickinson Well, I thought wrong… I tried on a clean install but it did not work, even having done absolutely all the updates. I probably got lucky because I simply reset Windows 7 with the upgrade mode, so the necessary certificate was probably still here. I think the problem is the same as for curl. curl must have a certificate with him to work on Windows, so there is one provided with curl. It is probably the same for Stubby, which you are fixing in this bug if I understood?

**Comment by saradickinson** [comment] 2018-03-02 14:29
The Stubby for Windows installer comes with its own certificate store which is why I don't think this is the same issue as the curl problem (where the system has no certificate store by default).  
Does it give this message for all the upstreams or do you have a single upstream configured?
Also, I'm planning to update the Windows installer in the next couple of weeks with the 1.4 release of getdns which includes the option to use just a SPKI pin for an upstream (not requiring a cert) which would at least provide a workaround for you.

**Comment by Kdmeizk** [comment] 2018-03-02 16:34
> Does it give this message for all the upstreams

Yes it gives the same message for any upstream.

> The Stubby for Windows installer comes with its own certificate store

How it works? Is this a file included with the others or Windows installer puts it in the Registry for example? Maybe I can check if this certificate exists after the installation of Stubby.

**Comment by jankal** [comment] 2018-04-02 12:29
This is also related if one wants to setup cloudflares 1.1.1.1 DNS-over-TLS servers via Stubby on Windows.
Following configuration should work:
```yaml
upstream_recursive_servers:
  - address_data: 1.1.1.1
    tls_pubkey_pinset:
      - digest: "sha256"
        value: 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
```
Unfortunatly it fails with a `Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"`

This should really be fixed! Why doesn't Stubby just use the Windows certificate store to validate the TLS certificates? - Even just a cacerts file would do it, so the users can edit it and add the required certificates if they want to set up their own DNS-over-TLS server within Stubby.

@saradickinson @wtoorop 
> This is important!

**Comment by jankal** [comment] 2018-04-02 12:33
See also #87

**Comment by george-chakhidze** [comment] 2018-04-02 12:58
I have same problem too: `Verify failed : Transport=TLS - *Failure* -  (20) "unable to get local issuer certificate"`.
OS: **Windows**
Relevant entries from `stubby.yml`:

```yaml
upstream_recursive_servers:
# Quad9 DNS-over-TLS server
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: ZMZ1T16d9Qc5uvRpUn/mu6fh4+IdoJGOEKjANut91Io=
    tls_port: 853
# CloudFlare DNS-over-TLS server
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
    tls_port: 853
```

I have manually downloaded entire chains of X.509 certificates from both `9.9.9.9:853` and `1.1.1.1:853` endpoints and installed in Windows certificate store. Did not help.

**Comment by Viktor45** [comment] 2018-04-02 17:25
i have same issues on my entware router and fixed this with
`opkg install ca-certificates`
`opkg install ca-bundle`

i hope this helps a lot to somebody, who is setting stubby first time

**Comment by wtoorop** [comment] 2018-04-03 12:07
@jankal Yes this is important and has been adressed in the getdns-1.4.0 release (or should have been adressed).

When compiled with OpenSSL 1.1.0 or higher it will use the native DANE functions for pin authentication.  A pin authentication is then enough, and no Certificate Authority needs to vouch for the name then.  With OpenSSL 1.0.2 or higher Viktor's ssl_dane library will be used.

Which version of getdns do you use?  The output of the `stubby -i` command (or stubby.exe -i) should tell...

**Comment by sergeevabc** [comment] 2018-04-03 12:29
@wtoorop, since I have the same issue as @jankal, let me reply as well.

```yaml
"api_version_number": 132058112,
"api_version_string": <bindata of "December 2015">,
"compilation_comment": <bindata of "getdns 1.2.2-rc1 configured on 2"...>

"openssl_build_version_number": 268443855,
"resolution_type": GETDNS_RESOLUTION_STUB,
"version_number": 16908737,
"version_string": <bindata of "1.2.2-rc1">
```

**Comment by jankal** [comment] 2018-04-03 12:46
```
"api_version_number": 132058112,
  "api_version_string": <bindata of "December 2015">,
  "compilation_comment": <bindata of "getdns 1.2.2-rc1 configured on 2"...>,
  "default_hosts_location": <bindata of "C:\Windows\System32\Drivers\etc\"...>,
  "default_resolvconf_location": <bindata of "/etc/resolv.conf">,
  "default_trust_anchor_location": <bindata of "/mingw64/etc/unbound/getdns-root"...>,
  "implementation_string": <bindata of "https://getdnsapi.net">,
  "listen_addresses":
  [
    {
      "address_data": <bindata for 127.0.0.1>,
      "address_type": <bindata of "IPv4">,
      "port": 53
    },
    {
      "address_data": <bindata for ::1>,
      "address_type": <bindata of "IPv6">,
      "port": 53
    }
  ],
  "openssl_build_version_number": 268443855,
  "resolution_type": GETDNS_RESOLUTION_STUB,
  "version_number": 16908737,
  "version_string": <bindata of "1.2.2-rc1">
```

**Comment by wtoorop** [comment] 2018-04-03 12:50
@saradickinson We need to update the Windows build...

**Comment by wtoorop** [comment] 2018-04-03 12:52
Oh reading back I see that Sara mentioned all this earlier already.

We'll provide a Windows build with getdns-1.4.1 soon, with which you can work around the issue by providing a SPKI pin.

**Comment by wtoorop** [comment] 2018-04-03 12:56
Oh and 1.3.0 introduced configuration parameters for specifying the CA store, so it should work with that as well:https://getdnsapi.net/functions/getdns_context_set_tls_ca_path.html

So you can specify something like
```
set_tls_ca_path: "C:\ssl\certs
```
in stubby.yml.

**Comment by jankal** [comment] 2018-04-03 12:57
@wtoorop I only added this in here so you know it's even more important now, when everyone wants to use Stubby with 1.1.1.1. I hope, a new build will be provided soon (I haven't got any build environment installed right now, currently I only develop using Docker).

`set_tls_ca_path` seems to be the solution we've all been looking for.

**Comment by jankal** [comment] 2018-04-03 12:58
@wtoorop Is `set_tls_ca_file` also supported?

**Comment by wtoorop** [comment] 2018-04-03 13:06
Yes, all getdns_context_set_(*) works from the `.yml` file (so https://getdnsapi.net/functions/getdns_context_set_resolution_type.html  and all functions below it on that page) + all the extension settings, but I said it wrong.  You have to strip of `getdns_context_set_` in the `.yml` file.  So specifying a CA file:

```
tls_ca_file: "C:\ssl\certs.pem"
```

And to specify a CA path:
```
tls_ca_path: "C:\ssl\certs"
```

**Comment by jankal** [comment] 2018-04-03 13:07
@wtoorop You are awesome!

**Comment by wtoorop** [comment] 2018-04-03 13:08
Thanks! :-) 

I do think we still have to integrate with the native Windows CA store though...

**Comment by jankal** [comment] 2018-04-03 13:12
```
C:\Program Files\Stubby>"C:\Program Files\Stubby\stubby.exe" -C "C:\Program Files\Stubby\stubby.yml" -l
Could not configure context with config dict: The library did not have the requested API feature implemented.
Could not parse config file "C:\Program Files\Stubby\stubby.yml": The library did not have the requested API feature implemented.
```

**Comment by george-chakhidze** [comment] 2018-04-03 13:19
@jankal Current build of Stubby for Windows is bundled with `1.2.1rc-1` version of `getdns` — we must wait for new release...

**Comment by jankal** [comment] 2018-04-03 13:21
@george-chakhidze the hell you're right. I hate waiting.

**Comment by saradickinson** [comment] 2018-04-03 13:28
@wtoorop I'll work on updating the Windows installer asap

**Comment by saradickinson** [comment] 2018-04-05 10:26
Hi All,  A new Windows installer is a now available using getdns 1.4.1:
https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby
However note @wtoorop the ca_path/ca-file settings are not used for the Windows cert config in 1.4.1, the code currently just loads from the system root store. We'll need to fix this.
But this release should allow using just pins for validation as a workaround.

**Comment by wtoorop** [comment] 2018-04-23 13:05
@abelbeck Thanks.  This was actually quite a severe bug, which can be fixed with attached patch:

  - 
[0001-Force-trailing-0-with-string-config-settings.patch.gz](https://github.com/getdnsapi/stubby/files/1938281/0001-Force-trailing-0-with-string-config-settings.patch.gz)

**Comment by abelbeck** [comment] 2018-04-23 14:02
@wtoorop I can confirm your fix solves the issue.

Thanks for your prompt solution.

**Comment by saradickinson** [comment] 2018-05-04 09:57
Closing as I think all the issues are resolved.

**Closed by saradickinson** 2018-05-04 09:57 UTC
Labels: bug, duplicate

**Comment by Kdmeizk** [comment] 2018-05-11 01:04
@saradickinson 
https://github.com/getdnsapi/stubby/issues/46#issuecomment-367182901
https://github.com/getdnsapi/stubby/issues/46#issuecomment-367303730

You can remove the point about a possible Windows update required for certificate verification to work because Stubby works perfectly without any Windows update now :)

Here:
https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby#WindowsinstallerforStubby-KnownIssues

**Comment by Zamiell** [comment] 2019-10-02 20:40
I ran into this issue today with a vanilla Stubby installation on Windows 10. The error message of ` *FAILURE* no valid transports or upstreams available!` is fairly misleading, as it implies that the "stubby.yml" file has no configured upstream servers, or that the current configured upstream servers are not available to be contacted. (Neither of which is the case, because the real problem is certificate validation.)

@saradickinson Is it possible for a separate error message to be created, or the existing one changed, or something along those lines?

**Comment by wellloaded** [comment] 2021-08-01 18:24
I just wanted to add to this topic that the error in the subject happens also when the Internet connectivity becomes slowish/unreliable. It is common for me to see these entries in the log when my router is connected via 3G/4G and there's a temporary issue with the mobile provider.

So two points from myself:

1) Perhaps the Failure message could be a bit more descriptive to help troubleshooting. I bet there are a bunch of different root causes that generate the very same log entry. Ideally you will want one entry per root cause.

2) Can Stubby be re-thught to perform also over slow/unreliable networks? (rather than just fail)?

**Comment by wellloaded** [comment] 2021-08-04 19:05
It might be not the right context but I'm starting to wonder if a wireguard like approach (encryption peering  with no formal handshaking) would be more suitable for Stubby operations. I'm not suggesting to wireguard into the DNS resolver network but rather to use the same fast and painless end-to-end encryption idea. Of course that's not only Stubby and would need to come from the resolver side too, but it could be an improvement for sloppy networks and perhaps even improve the overall performance under normal conditions.

Just a thought
